"""recreate safety_events

Revision ID: 0de01c981a6c
Revises: b18538fb70bb
Create Date: 2026-05-29 00:24:04.339973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de01c981a6c'
down_revision: Union[str, Sequence[str], None] = 'b18538fb70bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS safety_events CASCADE')
    op.create_table('safety_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_events'))
    )
    op.create_index(op.f('ix_safety_events_idempotency_key'), 'safety_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_safety_events_trace_id'), 'safety_events', ['trace_id'], unique=False)
    op.create_index(op.f('ix_safety_events_user_id'), 'safety_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_events_user_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_trace_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_idempotency_key'), table_name='safety_events')
    op.drop_table('safety_events')
    # ### end Alembic commands ###
